### ISSUE TITLE
[FEAT]: Github Action 캐싱 기능 수정

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/MacC-Team-Vegeting#224]
## 💡 Issue

기존 캐싱 기능 작동하지 않는 문제
![image](https://user-images.githubusercontent.com/39371835/210674588-ce39aeb0-eec4-47a4-89b9-4a4bc274209c.png)

### 문제원인
1. Cache@v2로 했던 점
- 기존 팀에서 cache@v2로 사용했을 때, 정상적으로 작동되었기 때문에 그걸 그대로 하려고 했습니다
- 하지만 [공식 github action](https://github.com/actions/cache/issues/1054)에 문의결과 "캐시 사이즈가 0으로 나오기 때문에, 정상적으로 작동하지 않는 것이다."라고 들었고 보다 더 근본적인 문제의 해결책을 탐색하였습니다.
2. Sample Docs를 그대로 따라한 점
```yml
  uses: actions/cache@v3
  with:
    path: .build
    key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    restore-keys: |
      ${{ runner.os }}-spm-
```
- 기존 sample docs와 저는 configuration이 다를 수 있기 때문에 빌드 파일의 경로를 정확하게 지정해야 합니다.
- Swift에서 프로젝트에 package build file이 생성되는 공간은 /Users/runner/Library/Developer/Xcode/DerivedData/OurProject/Build 입니다.
## 📝  todo
- [ ] cache 지정 경로 추가
